version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_dev
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - migration

  migration:
    build:
      context: .
      dockerfile: migration.dockerfile
    tty: true
    stdin_open: true
    environment:
      DEV_POSTGRES_URL: postgres://postgres:password@db:5432/app_dev?sslmode=disable
    volumes:
      - .:/go/src/app
    depends_on:
      - db

